### ISSUE TITLE
A wallet for Linux.

### ISSUE THREAD

**Issue by Krot666** [GeldumProject/geldum#1]
Hello.
Why in your code there are no options for creating a purse, under UNIХ system?

**Comment by edwardlow** [comment]
Hi,
Yes, if you compile the geldum source code, you will have a terminal one.
If you want a GUI wallet, better go to https://github.com/geldumproject/geldum-gui and download the GUI wallet Source Code and compile following the instructions.

**Comment by edwardlow** [comment]
Closing as solved as there is compilation for Linux
