### ISSUE TITLE
Can't run it on OSX 10.12.6

### ISSUE THREAD

**Issue by Astxsilencer** [GeldumProject/geldum#4]
maybe missing some libs?
GUI version also doesn't work

**Comment by geldum** [comment]
Did you follow all the dependences instalation?

**Comment by Astxsilencer** [comment]
Be more specific, please. What dependences i must install? Thank You!

**Comment by Astxsilencer** [comment]
Find it and going to install/reinstall them. Still no success. After running /geldumd get message "Illegal instruction: 4"

**Comment by geldum** [comment]
Solved on discord, closing
